export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = 'CLEAR_MSEARCH_TEXT';
export const GET_SEARCH_TEXT = 'GET_SEARCH_TEXT';
export const SET_SELECT_OPTION = 'SET_SELECT_OPTION';
