export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const CREATE_USER = 'CREATE_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
